# site:
#     resource: "@SiteBundle/Controller/"
#     type:     annotation
#     prefix:   /

imie_blog:
    resource: "@ImieBlogBundle/Controller/BlogController.php"
    type:     annotation
    prefix:   /

tv:
    resource: "@TvBundle/Controller/DefaultController.php"
    type:     annotation

imie_blog_image:
    resource: "@ImieBlogBundle/Controller/ImageController.php"
    type:     annotation

imie_blog_commentaire:
    resource: "@ImieBlogBundle/Controller/CommentaireController.php"
    type:     annotation

imie_blog_article:
    resource: "@ImieBlogBundle/Controller/ArticleController.php"
    type:     annotation

imie_blog_categorie:
    resource: "@ImieBlogBundle/Controller/CategorieController.php"
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"