imie_blog_index:
    path:     /
    defaults: { _controller: ImieBlogBundle:Blog:index }

imie_blog_ajouter:
    path: /ajouter
    defaults: { _controller: ImieBlogBundle:Blog:ajouter }

imie_blog_modifier:
    path: /modifier/{id}
    defaults: { _controller: ImieBlogBundle:Blog:modifier, id: -1 }
    requirements:
        categorie: \d+

imie_blog_supprimer:
    path: /supprimer/{id}
    defaults: { _controller: ImieBlogBundle:Blog:supprimer, id: -1 }
    requirements:
        categorie: \d+

imie_blog_voir:
    path: /voir/{id}
    defaults: { _controller: ImieBlogBundle:Blog:voir, id: -1 }
    requirements:
        categorie: \d+

imie_blog_ajouterCommentaire:
    path: /ajCommentaire
    defaults: { _controller: ImieBlogBundle:Blog:ajCommentaire }

imie_blog_supprimerCommentaire:
    path: /suppCommentaire/{id}
    defaults: { _controller: ImieBlogBundle:Blog:suppCommentaire, id: -1 }
    requirements:
        categorie: \d+

imie_blog_afficherTous:
    path: /afficherTous/{page}
    defaults: { _controller: ImieBlogBundle:Blog:afficherTous, page: 1 }
    requirements:
        categorie: \d+