<?php

namespace SiteBundle\Repository;

/**
 * EpisodeEnRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EpisodeEnRepository extends \Doctrine\ORM\EntityRepository
{
}
