<?php

namespace SiteBundle\Repository;

/**
 * EpisodeCommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EpisodeCommentRepository extends \Doctrine\ORM\EntityRepository
{
}
