<?php

namespace SiteBundle\Repository;

/**
 * EpisodeFrRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EpisodeFrRepository extends \Doctrine\ORM\EntityRepository
{
}
