<?php

namespace SiteBundle\Repository;

/**
 * RatingCommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RatingCommentRepository extends \Doctrine\ORM\EntityRepository
{
}
