<?php

namespace SiteBundle\Repository;

/**
 * RatingSeriesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RatingSeriesRepository extends \Doctrine\ORM\EntityRepository
{
}
