<?php

namespace SiteBundle\Repository;

/**
 * SeriesFrRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SeriesFrRepository extends \Doctrine\ORM\EntityRepository
{
}
