<?php

namespace SiteBundle\Repository;

/**
 * SeriesEnRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SeriesEnRepository extends \Doctrine\ORM\EntityRepository
{
}
