<?php

namespace Imie\BlogBundle\Repository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends \Doctrine\ORM\EntityRepository
{
		public function showAllByRecent(){
		//order by the most recent articles
		return $this->createQueryBuilder('art')
		->orderBy('art.date', 'DESC')
		->getQuery()
		->getResult();
	}
		public function showDetails($id){
		//order by the most recent articles
		return $this->createQueryBuilder('art')
		->where('art.id='.$id)
		->leftJoin('art.commentaires', 'com')
		->leftJoin('art.categories', 'cat')
		->leftJoin('art.image', 'img')
		->getQuery()
		->getSingleResult();
	}



}
