saving_cats:
    resource: "@SavingCatsBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

rest :
    type: rest
    resource: "routing_rest.yml"
    prefix: /api