<?php

namespace BdRentalBundle\Repository;

/**
 * BDRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BDRepository extends \Doctrine\ORM\EntityRepository
{
	public function getAllDispo(){
		//select * from BD inner join Location on 
		return $this->createQueryBuilder('bd')
		->leftJoin('bd.locations', 'l')
		->getQuery()
		->getResult();
	}


}
